title = "Gitleaks config"

[allowlist]
description = "Разрешить распространённые ложные срабатывания"
regexes = [
  '''(?i)AKIA[0-9A-Z]{16}''', # AWS
]
files = [
  '''.gitignore''',
  '''.yamllint.yml''',
  '''.gitleaks.toml''',
]

[rules]
# Блокировать попадание секретов напрямую в конфиги
[[rules]]
description = "Общий секрет"
regex = '''(?i)(password|secret|token|api[_-]?key)\s*[:=]\s*['"][A-Za-z0-9\-\._]+['"]'''
